# Generated by Django 4.2.7 on 2024-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_notification_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='cart_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
